resolver: lts-12.10
packages:
- .
extra-deps:
- git: https://github.com/NorfairKing/cursor-brick.git
  commit: 4187fb5e8e3d2b046fc942a7b47cc0fbac75f006
  subdirs:
    - cursor-brick
- git: https://github.com/NorfairKing/cursor.git
  commit: 9a83adbf713ab2874daeb082f10f30e5a07c2d70
  subdirs:
    - cursor
    - cursor-gen
- git: https://github.com/NorfairKing/validity.git
  commit: f127f52cda8d7271e7ec38c9d722e0112c12ae2c
  subdirs:
  - genvalidity
  - genvalidity-aeson
  - genvalidity-bytestring
  - genvalidity-containers
  - genvalidity-hspec
  - genvalidity-hspec-aeson
  - genvalidity-hspec-binary
  - genvalidity-hspec-cereal
  - genvalidity-hspec-hashable
  - genvalidity-hspec-optics
  - genvalidity-path
  - genvalidity-property
  - genvalidity-scientific
  - genvalidity-text
  - genvalidity-time
  - genvalidity-unordered-containers
  - genvalidity-uuid
  - genvalidity-vector
  - validity
  - validity-aeson
  - validity-bytestring
  - validity-containers
  - validity-path
  - validity-primitive
  - validity-scientific
  - validity-text
  - validity-time
  - validity-unordered-containers
  - validity-uuid
  - validity-vector
